packages:
  - packages/*
  - apps/*

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

packageImportMethod: clone-or-copy

patchedDependencies:
  '@nx/maven@22.5.1': patches/@nx__maven@22.5.1.patch
