name: Nx Release

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - ".nx/version-plans/**"
  push:
    branches:
      - main
    paths:
      - ".nx/version-plans/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:
  release:
    name: Nx Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: pagopa/dx/.github/workflows/release-v2.yaml@feat-add-summary-comment-pr-nx-release-action
    with:
      environment: infra-dev-ci
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
