name: Release

on:
  push:
    branches:
      - main
    paths:
      - ".nx/version-plans/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: pagopa/dx/.github/workflows/release-v1.yaml@feat-add-nx-release-support-test
    with:
      environment: infra-dev-ci
      mode: create-pr
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
