name: Nx Release

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - ".nx/version-plans/**"
  push:
    branches:
      - main
    paths:
      - ".nx/version-plans/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:
  release:
    name: Nx Release
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: pagopa/dx/.github/workflows/release-v2.yaml@use-regex-for-tags-release-website-to-azure
    with:
      environment: infra-dev-ci
    secrets:
      app-client-id: ${{ secrets.GH_APP_RELEASE_CLIENT_ID }}
      app-private-key: ${{ secrets.GH_APP_RELEASE_APP_KEY }}
